<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="OpenText Functional Testing" productVer="24.4" os="Windows 11" host="LENOVO-L14-GEN-"><DocLocation><![CDATA[D:\UFT Project\Web\Checkout_BillingAddress]]></DocLocation></General>
<Doc rID="T1"   productName= "OpenText Functional Testing"  >
<DName><![CDATA[Checkout_BillingAddress]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action_Checkout_BillingAddress]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Checkout]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[17-12-2024 - 11:50:06]]></Time>
<TimeTick>1734416406</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Checkout]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[17-12-2024 - 11:50:06]]></Time>
<TimeTick>1734416406</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.FirstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Dhanya"]]></Details>
<Time><![CDATA[17-12-2024 - 11:50:06]]></Time>
<TimeTick>1734416406</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="11" Source="Action_Checkout_BillingAddress" SourceLine="0" >
<Disp><![CDATA[BillingNewAddress.FirstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.LastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rakesh"]]></Details>
<Time><![CDATA[17-12-2024 - 11:50:06]]></Time>
<TimeTick>1734416406</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" Source="Action_Checkout_BillingAddress" SourceLine="1" >
<Disp><![CDATA[BillingNewAddress.LastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.Address1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["DD SilverStone"]]></Details>
<Time><![CDATA[17-12-2024 - 11:50:06]]></Time>
<TimeTick>1734416406</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Action_Checkout_BillingAddress" SourceLine="2" >
<Disp><![CDATA[BillingNewAddress.Address1.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.Address2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Vaduthala"]]></Details>
<Time><![CDATA[17-12-2024 - 11:50:06]]></Time>
<TimeTick>1734416406</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="Action_Checkout_BillingAddress" SourceLine="3" >
<Disp><![CDATA[BillingNewAddress.Address2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.City.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Kochi"]]></Details>
<Time><![CDATA[17-12-2024 - 11:50:06]]></Time>
<TimeTick>1734416406</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" Source="Action_Checkout_BillingAddress" SourceLine="4" >
<Disp><![CDATA[BillingNewAddress.City.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.Company.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["IGS"]]></Details>
<Time><![CDATA[17-12-2024 - 11:50:06]]></Time>
<TimeTick>1734416406</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="21" Source="Action_Checkout_BillingAddress" SourceLine="5" >
<Disp><![CDATA[BillingNewAddress.Company.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.Email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test@igs.com"]]></Details>
<Time><![CDATA[17-12-2024 - 11:50:06]]></Time>
<TimeTick>1734416406</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="23" Source="Action_Checkout_BillingAddress" SourceLine="6" >
<Disp><![CDATA[BillingNewAddress.Email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.FaxNumber.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7637677322"]]></Details>
<Time><![CDATA[17-12-2024 - 11:50:06]]></Time>
<TimeTick>1734416406</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="25" Source="Action_Checkout_BillingAddress" SourceLine="7" >
<Disp><![CDATA[BillingNewAddress.FaxNumber.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.PhoneNumber.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7766368999"]]></Details>
<Time><![CDATA[17-12-2024 - 11:50:06]]></Time>
<TimeTick>1734416406</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="27" Source="Action_Checkout_BillingAddress" SourceLine="9" >
<Disp><![CDATA[BillingNewAddress.PhoneNumber.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.ZipPostalCod.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["682023"]]></Details>
<Time><![CDATA[17-12-2024 - 11:50:06]]></Time>
<TimeTick>1734416406</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="29" Source="Action_Checkout_BillingAddress" SourceLine="10" >
<Disp><![CDATA[BillingNewAddress.ZipPostalCod.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.CountryId.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["India"]]></Details>
<Time><![CDATA[17-12-2024 - 11:50:07]]></Time>
<TimeTick>1734416407</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="31" Source="Action_Checkout_BillingAddress" SourceLine="11" >
<Disp><![CDATA[BillingNewAddress.CountryId.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.StateProvinc.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Other (Non US)"]]></Details>
<Time><![CDATA[17-12-2024 - 11:50:07]]></Time>
<TimeTick>1734416407</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="33" Source="Action_Checkout_BillingAddress" SourceLine="12" >
<Disp><![CDATA[BillingNewAddress.StateProvinc.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Continue.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-12-2024 - 11:50:07]]></Time>
<TimeTick>1734416407</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="35" Source="Action_Checkout_BillingAddress" SourceLine="13" >
<Disp><![CDATA[Continue.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="10" Source="Action_Checkout_BillingAddress" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop. Checkout]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" Source="Action_Checkout_BillingAddress" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop. Checkout]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="17-12-2024 - 11:50:06" eTime="17-12-2024 - 11:50:07" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[Action_Checkout_BillingAddress Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[Checkout_BillingAddress Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="17-12-2024 - 11:50:04" eTime="17-12-2024 - 11:50:07" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test Checkout_BillingAddress Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>