<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="OpenText Functional Testing" productVer="24.4" os="Windows 11" host="LENOVO-L14-GEN-"><DocLocation><![CDATA[D:\UFT Project\Web\E2E_Shopping]]></DocLocation></General>
<Doc rID="T1"   productName= "OpenText Functional Testing"  >
<DName><![CDATA[E2E_Shopping]]></DName>
<Res><![CDATA[Res20]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action_Shopping]]></AName>
<Action rID="T5">
<AName><![CDATA[Action_Login [Login]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[19-12-2024 - 14:06:52]]></Time>
<TimeTick>1734597412</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[19-12-2024 - 14:06:52]]></Time>
<TimeTick>1734597412</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" Source="Action_Login [Login]" SourceLine="2" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" Source="Action_Login [Login]" SourceLine="2" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[19-12-2024 - 14:07:12]]></Time>
<TimeTick>1734597432</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop.Maximize]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-12-2024 - 14:07:12]]></Time>
<TimeTick>1734597432</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Action_Login [Login]" SourceLine="3" >
<Disp><![CDATA[Demo Web Shop.Maximize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop - Landing Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19-12-2024 - 14:07:12]]></Time>
<TimeTick>1734597432</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Log in.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-12-2024 - 14:07:12]]></Time>
<TimeTick>1734597432</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="18" Source="Action_Login [Login]" SourceLine="8" >
<Disp><![CDATA[Log in.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="17" Source="Action_Login [Login]" SourceLine="8" >
<Disp><![CDATA[Demo Web Shop - Landing Page]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19-12-2024 - 14:07:14]]></Time>
<TimeTick>1734597434</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["rakesh_demo@gmail.com"]]></Details>
<Time><![CDATA[19-12-2024 - 14:07:14]]></Time>
<TimeTick>1734597434</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="21" Source="Action_Login [Login]" SourceLine="10" >
<Disp><![CDATA[Email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Ramos@12345"]]></Details>
<Time><![CDATA[19-12-2024 - 14:07:15]]></Time>
<TimeTick>1734597435</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="23" Source="Action_Login [Login]" SourceLine="11" >
<Disp><![CDATA[Password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Log in.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-12-2024 - 14:07:15]]></Time>
<TimeTick>1734597435</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="25" Source="Action_Login [Login]" SourceLine="12" >
<Disp><![CDATA[Log in.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="20" Source="Action_Login [Login]" SourceLine="10" >
<Disp><![CDATA[Demo Web Shop. Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop - Landing Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19-12-2024 - 14:07:36]]></Time>
<TimeTick>1734597456</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA["Logged_Email"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[19-12-2024 - 14:07:36]]></Time>
<TimeTick>1734597456</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="65" status="Warning" >
<Disp><![CDATA["Logged_Email"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA["Logged_Email"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=*@gmail.com<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (87 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
text=*@gmail.com<SPAN class=Failed> (Skipped)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 87 matches)</SPAN><br>class=account<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>name=rakesh_demo@gmail.com<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>href=https://demowebshop.tricentis.com/customer/info<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>acc_name=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[19-12-2024 - 14:07:36]]></Time>
<TimeTick>1734597456</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="66" >
<Disp><![CDATA["Logged_Email"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="64" status="Warning" >
<Disp><![CDATA[Demo Web Shop - Landing Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="14" status="Warning" Source="Action_Login [Login]" SourceLine="3" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[ Successfully Logged in with rakesh_demo@gmail.com]]></Obj>
<Details ><![CDATA[ Successfully Logged in with rakesh_demo@gmail.com]]></Details>
<Time><![CDATA[19-12-2024 - 14:07:37]]></Time>
<TimeTick>1734597457</TimeTick>
<NodeArgs eType="User" icon="13" nRep="67" status="Passed" >
<Disp><![CDATA[ Successfully Logged in with rakesh_demo@gmail.com]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="19-12-2024 - 14:06:48" eTime="19-12-2024 - 14:07:37" passed="2" failed="0" warnings="1" ><Param paramInOut = "In"><ParamName><![CDATA[Email]]></ParamName><ParamVal><![CDATA[rakesh_demo@gmail.com]]></ParamVal>
</Param>
<Param paramInOut = "In"><ParamName><![CDATA[Password]]></ParamName><ParamVal><![CDATA[Ramos@12345]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Warning" >
<Disp><![CDATA[Action_Login [Login] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T20">
<AName><![CDATA[ShoppingProducts [SelectProducts]]]></AName>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[19-12-2024 - 14:07:59]]></Time>
<TimeTick>1734597479</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop - Shopping Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19-12-2024 - 14:07:59]]></Time>
<TimeTick>1734597479</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Apparel & Shoes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-12-2024 - 14:07:59]]></Time>
<TimeTick>1734597479</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="73" Source="ShoppingProducts [SelectProducts]" SourceLine="1" >
<Disp><![CDATA[Apparel & Shoes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[AIUtil.SetContext]]></Obj>
<Details plainTxt="False" ><![CDATA[Set context Browser("[ Demo Web Shop. Apparel & Shoes ]") for AIUtil]]></Details>
<Time><![CDATA[19-12-2024 - 14:08:08]]></Time>
<TimeTick>1734597488</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="74" nType="AIUtil" Source="ShoppingProducts [SelectProducts]" SourceLine="8" >
<Disp><![CDATA[AIUtil.SetContext]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[AIUtil.FindTextBlock("Add to cart", micFromLeft, 3).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-12-2024 - 14:08:10]]></Time>
<TimeTick>1734597490</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="76" Source="ShoppingProducts [SelectProducts]" SourceLine="9" >
<Disp><![CDATA[AIUtil.FindTextBlock("Add to cart", micFromLeft, 3).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[AIUtil.FindTextBlock("Add to cart", micFromLeft, 4).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-12-2024 - 14:08:14]]></Time>
<TimeTick>1734597494</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="78" Source="ShoppingProducts [SelectProducts]" SourceLine="10" >
<Disp><![CDATA[AIUtil.FindTextBlock("Add to cart", micFromLeft, 4).Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="72" Source="ShoppingProducts [SelectProducts]" SourceLine="1" >
<Disp><![CDATA[Demo Web Shop - Shopping Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="71" Source="ShoppingProducts [SelectProducts]" SourceLine="1" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="19-12-2024 - 14:07:37" eTime="19-12-2024 - 14:08:14" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="69" >
<Disp><![CDATA[ShoppingProducts [SelectProducts] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T27">
<AName><![CDATA[Action_ShoppingCart [ShoppingCart]]]></AName>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ shopping cart ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:41]]></Time>
<TimeTick>1734597881</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="82" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="7" >
<Disp><![CDATA[[ shopping cart ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:43]]></Time>
<TimeTick>1734597883</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop- Shopping Cart]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:43]]></Time>
<TimeTick>1734597883</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[ProductTable.RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:43]]></Time>
<TimeTick>1734597883</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="86" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="16" >
<Disp><![CDATA[ProductTable.RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:44]]></Time>
<TimeTick>1734597884</TimeTick>
<NodeArgs eType="General" icon="15" nRep="88" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:44]]></Time>
<TimeTick>1734597884</TimeTick>
<NodeArgs eType="General" icon="15" nRep="89" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:44]]></Time>
<TimeTick>1734597884</TimeTick>
<NodeArgs eType="General" icon="15" nRep="90" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="85" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="16" >
<Disp><![CDATA[Demo Web Shop- Shopping Cart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="84" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="16" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[Blue Jeans]]></Obj>
<Details ><![CDATA[Blue Jeans is selected and is displayed in the Cart]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:44]]></Time>
<TimeTick>1734597884</TimeTick>
<NodeArgs eType="User" icon="13" nRep="91" status="Passed" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="32" >
<Disp><![CDATA[Blue Jeans]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:44]]></Time>
<TimeTick>1734597884</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop- Shopping Cart]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:44]]></Time>
<TimeTick>1734597884</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:44]]></Time>
<TimeTick>1734597884</TimeTick>
<NodeArgs eType="General" icon="15" nRep="94" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:44]]></Time>
<TimeTick>1734597884</TimeTick>
<NodeArgs eType="General" icon="15" nRep="95" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:44]]></Time>
<TimeTick>1734597884</TimeTick>
<NodeArgs eType="General" icon="15" nRep="96" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="93" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="23" >
<Disp><![CDATA[Demo Web Shop- Shopping Cart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="92" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="23" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[Casual Golf Belt]]></Obj>
<Details ><![CDATA[Casual Golf Belt is selected and is displayed in the Cart]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:44]]></Time>
<TimeTick>1734597884</TimeTick>
<NodeArgs eType="User" icon="13" nRep="97" status="Passed" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="32" >
<Disp><![CDATA[Casual Golf Belt]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:44]]></Time>
<TimeTick>1734597884</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop- Shopping Cart]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:44]]></Time>
<TimeTick>1734597884</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Sub-Total:.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[1, 2]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:44]]></Time>
<TimeTick>1734597884</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="101" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="38" >
<Disp><![CDATA[Sub-Total:.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[termsofservice.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:44]]></Time>
<TimeTick>1734597884</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="103" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="39" >
<Disp><![CDATA[termsofservice.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Checkout.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-12-2024 - 14:14:44]]></Time>
<TimeTick>1734597884</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="105" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="40" >
<Disp><![CDATA[Checkout.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="100" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="38" >
<Disp><![CDATA[Demo Web Shop- Shopping Cart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="99" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="38" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="19-12-2024 - 14:14:14" eTime="19-12-2024 - 14:14:44" passed="2" failed="0" warnings="0" ><Param paramInOut = "In"><ParamName><![CDATA[Products]]></ParamName><ParamVal><![CDATA[Blue Jeans|Casual Golf Belt]]></ParamVal>
</Param>
<Param paramInOut = "Out"><ParamName><![CDATA[SubTotal_out]]></ParamName><ParamVal><![CDATA[7.00]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="5" nRep="80" status="Passed" >
<Disp><![CDATA[Action_ShoppingCart [ShoppingCart] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T47">
<AName><![CDATA[Action_Checkout_BillingAddress [Checkout_BillingAddress]]]></AName>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[19-12-2024 - 14:15:05]]></Time>
<TimeTick>1734597905</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Checkout]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19-12-2024 - 14:15:05]]></Time>
<TimeTick>1734597905</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.FirstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Dhanya"]]></Details>
<Time><![CDATA[19-12-2024 - 14:15:05]]></Time>
<TimeTick>1734597905</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="111" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="0" >
<Disp><![CDATA[BillingNewAddress.FirstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.LastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rakesh"]]></Details>
<Time><![CDATA[19-12-2024 - 14:15:05]]></Time>
<TimeTick>1734597905</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="113" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="1" >
<Disp><![CDATA[BillingNewAddress.LastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.Address1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["DD SilverStone"]]></Details>
<Time><![CDATA[19-12-2024 - 14:15:05]]></Time>
<TimeTick>1734597905</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="115" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="2" >
<Disp><![CDATA[BillingNewAddress.Address1.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.Address2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Vaduthala"]]></Details>
<Time><![CDATA[19-12-2024 - 14:15:05]]></Time>
<TimeTick>1734597905</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="117" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="3" >
<Disp><![CDATA[BillingNewAddress.Address2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.City.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Kochi"]]></Details>
<Time><![CDATA[19-12-2024 - 14:15:05]]></Time>
<TimeTick>1734597905</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="119" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="4" >
<Disp><![CDATA[BillingNewAddress.City.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.Company.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["IGS"]]></Details>
<Time><![CDATA[19-12-2024 - 14:15:05]]></Time>
<TimeTick>1734597905</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="121" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="5" >
<Disp><![CDATA[BillingNewAddress.Company.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.Email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test@igs.com"]]></Details>
<Time><![CDATA[19-12-2024 - 14:15:05]]></Time>
<TimeTick>1734597905</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="123" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="6" >
<Disp><![CDATA[BillingNewAddress.Email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.FaxNumber.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7637677322"]]></Details>
<Time><![CDATA[19-12-2024 - 14:15:05]]></Time>
<TimeTick>1734597905</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="125" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="7" >
<Disp><![CDATA[BillingNewAddress.FaxNumber.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.PhoneNumber.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7766368999"]]></Details>
<Time><![CDATA[19-12-2024 - 14:15:06]]></Time>
<TimeTick>1734597906</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="127" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="9" >
<Disp><![CDATA[BillingNewAddress.PhoneNumber.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.ZipPostalCod.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["682023"]]></Details>
<Time><![CDATA[19-12-2024 - 14:15:06]]></Time>
<TimeTick>1734597906</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="129" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="10" >
<Disp><![CDATA[BillingNewAddress.ZipPostalCod.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.CountryId.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["India"]]></Details>
<Time><![CDATA[19-12-2024 - 14:15:06]]></Time>
<TimeTick>1734597906</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="131" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="11" >
<Disp><![CDATA[BillingNewAddress.CountryId.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.StateProvinc.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Other (Non US)"]]></Details>
<Time><![CDATA[19-12-2024 - 14:15:06]]></Time>
<TimeTick>1734597906</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="133" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="12" >
<Disp><![CDATA[BillingNewAddress.StateProvinc.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Continue_BillingAddr.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-12-2024 - 14:15:06]]></Time>
<TimeTick>1734597906</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="135" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="13" >
<Disp><![CDATA[Continue_BillingAddr.Click]]></Disp>
</NodeArgs>
</Step>