<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="OpenText Functional Testing" productVer="24.4" os="Windows 11" host="LENOVO-L14-GEN-"><DocLocation><![CDATA[D:\UFT Project\Web\E2E_Shopping]]></DocLocation></General>
<Doc rID="T1"   productName= "OpenText Functional Testing"  >
<DName><![CDATA[E2E_Shopping]]></DName>
<Res><![CDATA[Res13]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action_Shopping]]></AName>
<Action rID="T5">
<AName><![CDATA[Action_Login [Login]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[16-12-2024 - 17:07:56]]></Time>
<TimeTick>1734349076</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[16-12-2024 - 17:07:56]]></Time>
<TimeTick>1734349076</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" Source="Action_Login [Login]" SourceLine="0" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" Source="Action_Login [Login]" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[16-12-2024 - 17:08:16]]></Time>
<TimeTick>1734349096</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop.Maximize]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-12-2024 - 17:08:16]]></Time>
<TimeTick>1734349096</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Action_Login [Login]" SourceLine="1" >
<Disp><![CDATA[Demo Web Shop.Maximize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop - Landing Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[16-12-2024 - 17:08:16]]></Time>
<TimeTick>1734349096</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Log in.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-12-2024 - 17:08:16]]></Time>
<TimeTick>1734349096</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="18" Source="Action_Login [Login]" SourceLine="6" >
<Disp><![CDATA[Log in.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="17" Source="Action_Login [Login]" SourceLine="6" >
<Disp><![CDATA[Demo Web Shop - Landing Page]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[16-12-2024 - 17:08:18]]></Time>
<TimeTick>1734349098</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["rakesh_demo@gmail.com"]]></Details>
<Time><![CDATA[16-12-2024 - 17:08:18]]></Time>
<TimeTick>1734349098</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="21" Source="Action_Login [Login]" SourceLine="8" >
<Disp><![CDATA[Email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Ramos@12345"]]></Details>
<Time><![CDATA[16-12-2024 - 17:08:18]]></Time>
<TimeTick>1734349098</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="23" Source="Action_Login [Login]" SourceLine="9" >
<Disp><![CDATA[Password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Log in.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-12-2024 - 17:08:19]]></Time>
<TimeTick>1734349099</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="25" Source="Action_Login [Login]" SourceLine="10" >
<Disp><![CDATA[Log in.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="20" Source="Action_Login [Login]" SourceLine="8" >
<Disp><![CDATA[Demo Web Shop. Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop - Landing Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[16-12-2024 - 17:08:40]]></Time>
<TimeTick>1734349120</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA["Logged_Email"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[16-12-2024 - 17:08:40]]></Time>
<TimeTick>1734349120</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="64" status="Warning" >
<Disp><![CDATA["Logged_Email"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA["Logged_Email"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=*@gmail.com<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (87 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
text=*@gmail.com<SPAN class=Failed> (Skipped)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 87 matches)</SPAN><br>class=account<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>name=rakesh_demo@gmail.com<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>href=https://demowebshop.tricentis.com/customer/info<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>acc_name=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[16-12-2024 - 17:08:40]]></Time>
<TimeTick>1734349120</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="65" >
<Disp><![CDATA["Logged_Email"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="63" status="Warning" >
<Disp><![CDATA[Demo Web Shop - Landing Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="14" status="Warning" Source="Action_Login [Login]" SourceLine="1" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[ Successfully Logged in with rakesh_demo@gmail.com]]></Obj>
<Details ><![CDATA[ Successfully Logged in with rakesh_demo@gmail.com]]></Details>
<Time><![CDATA[16-12-2024 - 17:08:41]]></Time>
<TimeTick>1734349121</TimeTick>
<NodeArgs eType="User" icon="13" nRep="66" status="Passed" >
<Disp><![CDATA[ Successfully Logged in with rakesh_demo@gmail.com]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="16-12-2024 - 17:07:55" eTime="16-12-2024 - 17:08:41" passed="2" failed="0" warnings="1" ><Param paramInOut = "In"><ParamName><![CDATA[Email]]></ParamName><ParamVal><![CDATA[rakesh_demo@gmail.com]]></ParamVal>
</Param>
<Param paramInOut = "In"><ParamName><![CDATA[Password]]></ParamName><ParamVal><![CDATA[Ramos@12345]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Warning" >
<Disp><![CDATA[Action_Login [Login] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T20">
<AName><![CDATA[ShoppingProducts [SelectProducts]]]></AName>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[16-12-2024 - 17:09:03]]></Time>
<TimeTick>1734349143</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop - Shopping Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[16-12-2024 - 17:09:03]]></Time>
<TimeTick>1734349143</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Apparel & Shoes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-12-2024 - 17:09:03]]></Time>
<TimeTick>1734349143</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="72" Source="ShoppingProducts [SelectProducts]" SourceLine="1" >
<Disp><![CDATA[Apparel & Shoes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[AIUtil.SetContext]]></Obj>
<Details plainTxt="False" ><![CDATA[Set context Browser("[ Demo Web Shop. Apparel & Shoes ]") for AIUtil]]></Details>
<Time><![CDATA[16-12-2024 - 17:09:12]]></Time>
<TimeTick>1734349152</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="73" nType="AIUtil" Source="ShoppingProducts [SelectProducts]" SourceLine="8" >
<Disp><![CDATA[AIUtil.SetContext]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[AIUtil.FindTextBlock("Add to cart", micFromLeft, 3).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-12-2024 - 17:09:14]]></Time>
<TimeTick>1734349154</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="75" Source="ShoppingProducts [SelectProducts]" SourceLine="9" >
<Disp><![CDATA[AIUtil.FindTextBlock("Add to cart", micFromLeft, 3).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[AIUtil.FindTextBlock("Add to cart", micFromLeft, 4).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-12-2024 - 17:09:18]]></Time>
<TimeTick>1734349158</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="77" Source="ShoppingProducts [SelectProducts]" SourceLine="10" >
<Disp><![CDATA[AIUtil.FindTextBlock("Add to cart", micFromLeft, 4).Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="71" Source="ShoppingProducts [SelectProducts]" SourceLine="1" >
<Disp><![CDATA[Demo Web Shop - Shopping Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="70" Source="ShoppingProducts [SelectProducts]" SourceLine="1" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="16-12-2024 - 17:08:41" eTime="16-12-2024 - 17:09:18" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="68" >
<Disp><![CDATA[ShoppingProducts [SelectProducts] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T27">
<AName><![CDATA[Action_ShoppingCart [ShoppingCart]]]></AName>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[16-12-2024 - 17:10:00]]></Time>
<TimeTick>1734349200</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Apparel]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[16-12-2024 - 17:10:00]]></Time>
<TimeTick>1734349200</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Shopping cart]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Shopping&nbsp;cart"&nbsp;(of&nbsp;class&nbsp;Link).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[16-12-2024 - 17:10:00]]></Time>
<TimeTick>1734349200</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Shopping cart]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>miccommentproperty = <br>Mercury Class = Link<br>Html Tag = A<br>_xpath = //LI[@id="topcartlink"]/A[normalize-space()="Shopping cart (2)"]<br>|Visible = -1<br>Text = Shopping cart (.*<br>Name = Shopping cart (2)<br>Html Id = <br>Href = https://demowebshop.tricentis.com/cart<br>DHTML Class = ico-cart<br>acc_name = <br>]]></Details>
<Time><![CDATA[16-12-2024 - 17:10:00]]></Time>
<TimeTick>1734349200</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="124" status="Warning" nType="Description" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Shopping cart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="123" status="Failed" nType="Run Error" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Shopping cart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="122" status="Failed" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop. Apparel]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="121" status="Failed" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[16-12-2024 - 17:10:00]]></Time>
<TimeTick>1734349200</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Shopping cart&quot; (of class Link).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (1): &quot;Browser(&quot;Demo Web Shop&quot;).Page(&quot;Demo Web Shop. Apparel&quot;).Link(&quot;Shopping cart&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[16-12-2024 - 17:10:00]]></Time>
<TimeTick>1734349200</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="126" status="Failed" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act4\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[58265542]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Apparel]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[16-12-2024 - 17:10:33]]></Time>
<TimeTick>1734349233</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Shopping cart]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Shopping&nbsp;cart"&nbsp;(of&nbsp;class&nbsp;Link).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[16-12-2024 - 17:10:33]]></Time>
<TimeTick>1734349233</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Shopping cart]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>miccommentproperty = <br>Mercury Class = Link<br>Html Tag = A<br>_xpath = //LI[@id="topcartlink"]/A[normalize-space()="Shopping cart (2)"]<br>|Visible = -1<br>Text = Shopping cart (.*<br>Name = Shopping cart (2)<br>Html Id = <br>Href = https://demowebshop.tricentis.com/cart<br>DHTML Class = ico-cart<br>acc_name = <br>]]></Details>
<Time><![CDATA[16-12-2024 - 17:10:33]]></Time>
<TimeTick>1734349233</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="170" status="Warning" nType="Description" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Shopping cart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="169" status="Failed" nType="Run Error" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Shopping cart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="168" status="Failed" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop. Apparel]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="125" status="Failed" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act4\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[58265542]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[16-12-2024 - 17:10:33]]></Time>
<TimeTick>1734349233</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Shopping cart&quot; (of class Link).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (1): &quot;Browser(&quot;Demo Web Shop&quot;).Page(&quot;Demo Web Shop. Apparel&quot;).Link(&quot;Shopping cart&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[16-12-2024 - 17:10:33]]></Time>
<TimeTick>1734349233</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="172" status="Failed" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act4\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[58265542]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Apparel]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[16-12-2024 - 17:11:07]]></Time>
<TimeTick>1734349267</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Shopping cart]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Shopping&nbsp;cart"&nbsp;(of&nbsp;class&nbsp;Link).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[16-12-2024 - 17:11:07]]></Time>
<TimeTick>1734349267</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Shopping cart]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>miccommentproperty = <br>Mercury Class = Link<br>Html Tag = A<br>_xpath = //LI[@id="topcartlink"]/A[normalize-space()="Shopping cart (2)"]<br>|Visible = -1<br>Text = Shopping cart (.*<br>Name = Shopping cart (2)<br>Html Id = <br>Href = https://demowebshop.tricentis.com/cart<br>DHTML Class = ico-cart<br>acc_name = <br>]]></Details>
<Time><![CDATA[16-12-2024 - 17:11:07]]></Time>
<TimeTick>1734349267</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="216" status="Warning" nType="Description" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Shopping cart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="215" status="Failed" nType="Run Error" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Shopping cart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="214" status="Failed" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop. Apparel]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="171" status="Failed" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act4\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[58265542]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[16-12-2024 - 17:11:07]]></Time>
<TimeTick>1734349267</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Shopping cart&quot; (of class Link).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (1): &quot;Browser(&quot;Demo Web Shop&quot;).Page(&quot;Demo Web Shop. Apparel&quot;).Link(&quot;Shopping cart&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[16-12-2024 - 17:11:08]]></Time>
<TimeTick>1734349268</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="218" status="Failed" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act4\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[58265542]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop- Shopping Cart]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[16-12-2024 - 17:11:38]]></Time>
<TimeTick>1734349298</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[ProductTable.RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-12-2024 - 17:11:38]]></Time>
<TimeTick>1734349298</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="221" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="8" >
<Disp><![CDATA[ProductTable.RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[16-12-2024 - 17:11:38]]></Time>
<TimeTick>1734349298</TimeTick>
<NodeArgs eType="General" icon="16" nRep="223" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[16-12-2024 - 17:12:23]]></Time>
<TimeTick>1734349343</TimeTick>
<NodeArgs eType="General" icon="16" nRep="224" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[16-12-2024 - 17:12:26]]></Time>
<TimeTick>1734349346</TimeTick>
<NodeArgs eType="General" icon="16" nRep="225" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[16-12-2024 - 17:12:26]]></Time>
<TimeTick>1734349346</TimeTick>
<NodeArgs eType="General" icon="16" nRep="226" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[16-12-2024 - 17:12:27]]></Time>
<TimeTick>1734349347</TimeTick>
<NodeArgs eType="General" icon="16" nRep="227" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[16-12-2024 - 17:12:27]]></Time>
<TimeTick>1734349347</TimeTick>
<NodeArgs eType="General" icon="16" nRep="228" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[16-12-2024 - 17:12:28]]></Time>
<TimeTick>1734349348</TimeTick>
<NodeArgs eType="General" icon="16" nRep="229" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="220" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="8" >
<Disp><![CDATA[Demo Web Shop- Shopping Cart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="217" status="Failed" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act4\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[58265542]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[Blue Jeans]]></Obj>
<Details ><![CDATA[Blue Jeans is selected and is displayed in the Cart]]></Details>
<Time><![CDATA[16-12-2024 - 17:12:30]]></Time>
<TimeTick>1734349350</TimeTick>
<NodeArgs eType="User" icon="13" nRep="230" status="Passed" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="22" >
<Disp><![CDATA[Blue Jeans]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[16-12-2024 - 17:12:30]]></Time>