<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="OpenText Functional Testing" productVer="24.4" os="Windows 11" host="LENOVO-L14-GEN-"><DocLocation><![CDATA[D:\UFT Project\Web\Confirmation]]></DocLocation></General>
<Doc rID="T1"   productName= "OpenText Functional Testing"  >
<DName><![CDATA[Confirmation]]></DName>
<Res><![CDATA[Res14]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action_Confirmation]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:22]]></Time>
<TimeTick>1734520822</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop_Confirmation]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:22]]></Time>
<TimeTick>1734520822</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Product(s).RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:22]]></Time>
<TimeTick>1734520822</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="11" Source="Action_Confirmation" SourceLine="6" >
<Disp><![CDATA[Product(s).RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:25]]></Time>
<TimeTick>1734520825</TimeTick>
<NodeArgs eType="General" icon="7" nRep="13" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:25]]></Time>
<TimeTick>1734520825</TimeTick>
<NodeArgs eType="General" icon="7" nRep="14" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:26]]></Time>
<TimeTick>1734520826</TimeTick>
<NodeArgs eType="General" icon="7" nRep="15" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:26]]></Time>
<TimeTick>1734520826</TimeTick>
<NodeArgs eType="General" icon="7" nRep="16" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:26]]></Time>
<TimeTick>1734520826</TimeTick>
<NodeArgs eType="General" icon="7" nRep="17" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:27]]></Time>
<TimeTick>1734520827</TimeTick>
<NodeArgs eType="General" icon="7" nRep="18" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:28]]></Time>
<TimeTick>1734520828</TimeTick>
<NodeArgs eType="General" icon="7" nRep="19" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="10" Source="Action_Confirmation" SourceLine="6" >
<Disp><![CDATA[Demo Web Shop_Confirmation]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" Source="Action_Confirmation" SourceLine="6" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[Blue Jeans]]></Obj>
<Details ><![CDATA[Blue Jeans is selected and is displayed in Checkout]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:28]]></Time>
<TimeTick>1734520828</TimeTick>
<NodeArgs eType="User" icon="8" nRep="20" status="Passed" Source="Action_Confirmation" SourceLine="20" >
<Disp><![CDATA[Blue Jeans]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:28]]></Time>
<TimeTick>1734520828</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop_Confirmation]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:28]]></Time>
<TimeTick>1734520828</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:28]]></Time>
<TimeTick>1734520828</TimeTick>
<NodeArgs eType="General" icon="7" nRep="23" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:29]]></Time>
<TimeTick>1734520829</TimeTick>
<NodeArgs eType="General" icon="7" nRep="24" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:31]]></Time>
<TimeTick>1734520831</TimeTick>
<NodeArgs eType="General" icon="7" nRep="25" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:31]]></Time>
<TimeTick>1734520831</TimeTick>
<NodeArgs eType="General" icon="7" nRep="26" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:31]]></Time>
<TimeTick>1734520831</TimeTick>
<NodeArgs eType="General" icon="7" nRep="27" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:32]]></Time>
<TimeTick>1734520832</TimeTick>
<NodeArgs eType="General" icon="7" nRep="28" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:32]]></Time>
<TimeTick>1734520832</TimeTick>
<NodeArgs eType="General" icon="7" nRep="29" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:33]]></Time>
<TimeTick>1734520833</TimeTick>
<NodeArgs eType="General" icon="7" nRep="30" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:33]]></Time>
<TimeTick>1734520833</TimeTick>
<NodeArgs eType="General" icon="7" nRep="31" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:33]]></Time>
<TimeTick>1734520833</TimeTick>
<NodeArgs eType="General" icon="7" nRep="32" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:34]]></Time>
<TimeTick>1734520834</TimeTick>
<NodeArgs eType="General" icon="7" nRep="33" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:35]]></Time>
<TimeTick>1734520835</TimeTick>
<NodeArgs eType="General" icon="7" nRep="34" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:35]]></Time>
<TimeTick>1734520835</TimeTick>
<NodeArgs eType="General" icon="7" nRep="35" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="22" >
<Disp><![CDATA[Demo Web Shop_Confirmation]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="21" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA[Casual Golf Belt]]></Obj>
<Details ><![CDATA[Casual Golf Belt is selected and is displayed in Checkout]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:36]]></Time>
<TimeTick>1734520836</TimeTick>
<NodeArgs eType="User" icon="8" nRep="36" status="Passed" Source="Action_Confirmation" SourceLine="20" >
<Disp><![CDATA[Casual Golf Belt]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:36]]></Time>
<TimeTick>1734520836</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop_Confirmation]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:36]]></Time>
<TimeTick>1734520836</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:36]]></Time>
<TimeTick>1734520836</TimeTick>
<NodeArgs eType="General" icon="7" nRep="39" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:36]]></Time>
<TimeTick>1734520836</TimeTick>
<NodeArgs eType="General" icon="7" nRep="40" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:38]]></Time>
<TimeTick>1734520838</TimeTick>
<NodeArgs eType="General" icon="7" nRep="41" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Sub-Total:.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[1, 2]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:39]]></Time>
<TimeTick>1734520839</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="43" Source="Action_Confirmation" SourceLine="28" >
<Disp><![CDATA[Sub-Total:.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:39]]></Time>
<TimeTick>1734520839</TimeTick>
<NodeArgs eType="General" icon="7" nRep="44" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:50]]></Time>
<TimeTick>1734520850</TimeTick>
<NodeArgs eType="General" icon="7" nRep="45" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="38" >
<Disp><![CDATA[Demo Web Shop_Confirmation]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="37" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj ><![CDATA[15.00]]></Obj>
<Details ><![CDATA[15.00 is  dislayed correctly]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:51]]></Time>
<TimeTick>1734520851</TimeTick>
<NodeArgs eType="User" icon="8" nRep="46" status="Passed" Source="Action_Confirmation" SourceLine="30" >
<Disp><![CDATA[15.00]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:51]]></Time>
<TimeTick>1734520851</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop_Confirmation]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:51]]></Time>
<TimeTick>1734520851</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:51]]></Time>
<TimeTick>1734520851</TimeTick>
<NodeArgs eType="General" icon="7" nRep="49" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA["Sub-Total:":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:52]]></Time>
<TimeTick>1734520852</TimeTick>
<NodeArgs eType="General" icon="7" nRep="51" >
<Disp><![CDATA["Sub-Total:":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA["Sub-Total:":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:52]]></Time>
<TimeTick>1734520852</TimeTick>
<NodeArgs eType="General" icon="7" nRep="52" >
<Disp><![CDATA["Sub-Total:":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:52]]></Time>
<TimeTick>1734520852</TimeTick>
<NodeArgs eType="General" icon="7" nRep="53" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:50:56]]></Time>
<TimeTick>1734520856</TimeTick>
<NodeArgs eType="General" icon="7" nRep="54" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA["Sub-Total:":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[18-12-2024 - 16:51:03]]></Time>
<TimeTick>1734520863</TimeTick>
<NodeArgs eType="General" icon="7" nRep="55" >
<Disp><![CDATA["Sub-Total:":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:51:03]]></Time>
<TimeTick>1734520863</TimeTick>
<NodeArgs eType="General" icon="7" nRep="56" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA["Sub-Total:":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:51:04]]></Time>
<TimeTick>1734520864</TimeTick>
<NodeArgs eType="General" icon="7" nRep="57" >
<Disp><![CDATA["Sub-Total:":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:51:04]]></Time>
<TimeTick>1734520864</TimeTick>
<NodeArgs eType="General" icon="7" nRep="58" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:51:05]]></Time>
<TimeTick>1734520865</TimeTick>
<NodeArgs eType="General" icon="7" nRep="59" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA["Sub-Total:":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:51:05]]></Time>
<TimeTick>1734520865</TimeTick>
<NodeArgs eType="General" icon="7" nRep="60" >
<Disp><![CDATA["Sub-Total:":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:51:05]]></Time>
<TimeTick>1734520865</TimeTick>
<NodeArgs eType="General" icon="7" nRep="61" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:51:06]]></Time>
<TimeTick>1734520866</TimeTick>
<NodeArgs eType="General" icon="7" nRep="62" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA["Sub-Total:":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:51:07]]></Time>
<TimeTick>1734520867</TimeTick>
<NodeArgs eType="General" icon="7" nRep="63" >
<Disp><![CDATA["Sub-Total:":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:51:07]]></Time>
<TimeTick>1734520867</TimeTick>
<NodeArgs eType="General" icon="7" nRep="64" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:51:11]]></Time>
<TimeTick>1734520871</TimeTick>
<NodeArgs eType="General" icon="7" nRep="65" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA["Product(s)":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[18-12-2024 - 16:51:16]]></Time>
<TimeTick>1734520876</TimeTick>
<NodeArgs eType="General" icon="7" nRep="66" >
<Disp><![CDATA["Product(s)":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[18-12-2024 - 16:51:31]]></Time>
<TimeTick>1734520891</TimeTick>
<NodeArgs eType="General" icon="9" nRep="67" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="48" >
<Disp><![CDATA[Demo Web Shop_Confirmation]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="47" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="18-12-2024 - 16:50:20" eTime="18-12-2024 - 16:51:31" passed="3" failed="0" warnings="0" ><Param paramInOut = "In"><ParamName><![CDATA[Products_checkout]]></ParamName><ParamVal><![CDATA[Blue Jeans|Casual Golf Belt]]></ParamVal>
</Param>
<Param paramInOut = "In"><ParamName><![CDATA[p_Subtotal]]></ParamName><ParamVal><![CDATA[15.00]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action_Confirmation Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Confirmation Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="18-12-2024 - 16:50:17" eTime="18-12-2024 - 16:51:31" passed="3" failed="0" warnings="0" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test Confirmation Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>